/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Test dependencies
    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testRuntimeOnly(libs.junit.platform.launcher)

    // Compile time deps
    compileOnly(libs.jetbrains.annotations)

    // Chicory
    api(libs.chicory.runtime)
    api(libs.chicory.wasm)

    // Bytebuddy
    api(libs.bytebuddy)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.test {
    useJUnitPlatform() // THIS IS THE CRITICAL LINE
    testLogging {
        events("passed", "skipped", "failed")
    }
}

sourceSets {
    create("generator") {
        java {
            srcDir("src/generator/java")
        }
        // This allows the generator to "see" your bridge classes
        compileClasspath += sourceSets.main.get().output
        runtimeClasspath += sourceSets.main.get().output
    }
}

val generatorImplementation: Configuration? by configurations.getting {
    extendsFrom(configurations.implementation.get())
}

tasks.register<JavaExec>("generateWasmHeaders") {
    group = "build"
    dependsOn(tasks.compileJava, tasks.getByName("compileGeneratorJava"))

    mainClass.set("quest.yu_vitaqua_fer_chronos.wasjvmbridge.tasks.generators.Runner")

    // Use the generator source set's classpath
    classpath = sourceSets["generator"].runtimeClasspath

    args(layout.projectDirectory.file("wasjvm_autogen.h").asFile.absolutePath)
}